name: Daily 09:00 PL build & deploy
on:
  schedule:
    - cron: "0 7 * * *"
    - cron: "0 8 * * *"
  workflow_dispatch: {}
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install pyyaml feedparser
      - name: Build issue (idempotent guard inside)
        env:
          RESET_SEEN: "0"
        run: |
          python generate_all.py
          mkdir -p site
          touch site/.nojekyll
      - name: Optional email send
        if: env.EMAIL_ENABLED == '1'
        env:
          EMAIL_ENABLED: ${{ secrets.EMAIL_ENABLED }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
        run: |
          set -e
          latest=$(ls -1 site | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}\.html$' | sort | tail -n1 || true)
          if [ -n "$latest" ] && [ "${EMAIL_ENABLED:-0}" = "1" ]; then
            python send_email.py "site/$latest"
          else
            echo "Email disabled or no daily file found."
          fi
      - name: Commit changes if any
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(ci): daily build $(date -u +%F)"
            git push
          else
            echo "No changes to commit."
          fi
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "site"
      - id: deployment
        uses: actions/deploy-pages@v4
